# Generated by Django 5.2.15 on 2026-09-15 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costcard', '0006_alter_costcard_karat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCardVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this revision was created.', verbose_name='Created At')),
                ('active', models.BooleanField(default=True, help_text='Whether this revision is currently active.', verbose_name='Active')),
                ('version', models.PositiveIntegerField(help_text='Sequential version number of the cost card.', verbose_name='Version')),
                ('data', models.JSONField(help_text='Complete snapshot of the cost card and its related data.', verbose_name='Data')),
                ('cost_card', models.ForeignKey(help_text='Cost card associated with this version.', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='costcard.costcard', verbose_name='Cost Card')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this revision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Cost Card Version',
                'verbose_name_plural': 'Cost Card Versions',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['cost_card'], name='revision_co_cost_ca_dbc3c4_idx'), models.Index(fields=['version'], name='revision_co_version_aff433_idx'), models.Index(fields=['active'], name='revision_co_active_2842ee_idx')],
                'constraints': [models.UniqueConstraint(fields=('cost_card', 'version'), name='unique_cost_card_version')],
            },
        ),
    ]
