# Generated by Django 5.2.15 on 2026-09-04 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0082_company_default_stone_rate_company_group_id_and_more'),
        ('costcard', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcard',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Jewelry category of this piece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards', to='master.jewelrycategory', verbose_name='Jewelry Category'),
        ),
        migrations.AddField(
            model_name='costcard',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer this cost card is prepared for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards_as_customer', to='company.company', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='costcard',
            name='finding_type',
            field=models.ForeignKey(blank=True, help_text='Finding type used on this piece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards', to='master.findingtype', verbose_name='Finding Type'),
        ),
        migrations.AddField(
            model_name='costcard',
            name='metal_purity',
            field=models.ForeignKey(blank=True, help_text='Metal purity grade used for this piece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards', to='master.metalpurity', verbose_name='Metal Purity'),
        ),
        migrations.AddField(
            model_name='costcard',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent cost card from which this card was copied.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_cards', to='costcard.costcard', verbose_name='Parent Cost Card'),
        ),
        migrations.AddField(
            model_name='costcard',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Jewelry sub-category of this piece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards', to='master.jewelrysubcategory', verbose_name='Jewelry Sub Category'),
        ),
        migrations.AddField(
            model_name='costcard',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor this cost card is raised against.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards_as_vendor', to='company.company', verbose_name='Vendor'),
        ),
    ]
