# Generated by Django 5.2.15 on 2026-09-04 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costcard', '0002_initial'),
        ('master', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcardcolorstoneline',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Color stone color.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_colorstone_lines', to='properties.colorstonecolor', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='costcardcolorstoneline',
            name='cost_card',
            field=models.ForeignKey(help_text='Cost card this color stone line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='colorstone_lines', to='costcard.costcard', verbose_name='Cost Card'),
        ),
        migrations.AddField(
            model_name='costcardcolorstoneline',
            name='cut',
            field=models.ForeignKey(blank=True, help_text='Color stone cut type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_colorstone_lines', to='properties.colorstonecut', verbose_name='Cut'),
        ),
        migrations.AddField(
            model_name='costcardcolorstoneline',
            name='mm_size',
            field=models.ForeignKey(blank=True, help_text='Color stone size.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_colorstone_lines', to='properties.colorstonesize', verbose_name='MM Size'),
        ),
        migrations.AddField(
            model_name='costcardcolorstoneline',
            name='quality',
            field=models.ForeignKey(blank=True, help_text='Color stone quality grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_colorstone_lines', to='properties.colorstonequality', verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='costcardcolorstoneline',
            name='rate_source',
            field=models.ForeignKey(blank=True, help_text='Color stone rate table row this line was originally copied from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_colorstone_lines', to='properties.colorstonerate', verbose_name='Rate Source'),
        ),
        migrations.AddField(
            model_name='costcardcolorstoneline',
            name='setting',
            field=models.ForeignKey(blank=True, help_text='Jewelry setting used for this color stone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_colorstone_lines', to='master.setting', verbose_name='Setting'),
        ),
        migrations.AddField(
            model_name='costcardcolorstoneline',
            name='shape',
            field=models.ForeignKey(blank=True, help_text='Color stone shape.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_colorstone_lines', to='properties.colorstoneshape', verbose_name='Shape'),
        ),
        migrations.AddField(
            model_name='costcardcolorstoneline',
            name='stone',
            field=models.ForeignKey(blank=True, help_text='Color stone type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_colorstone_lines', to='properties.colorstone', verbose_name='Stone'),
        ),
        migrations.AddField(
            model_name='costcarddiamondline',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Diamond color grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_diamond_lines', to='properties.diamondcolor', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='costcarddiamondline',
            name='cost_card',
            field=models.ForeignKey(help_text='Cost card this diamond line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='diamond_lines', to='costcard.costcard', verbose_name='Cost Card'),
        ),
        migrations.AddField(
            model_name='costcarddiamondline',
            name='cut',
            field=models.ForeignKey(blank=True, help_text='Diamond cut type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_diamond_lines', to='properties.diamondcut', verbose_name='Cut'),
        ),
        migrations.AddField(
            model_name='costcarddiamondline',
            name='mm_size',
            field=models.ForeignKey(blank=True, help_text='Diamond size.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_diamond_lines', to='properties.diamondsize', verbose_name='MM Size'),
        ),
        migrations.AddField(
            model_name='costcarddiamondline',
            name='quality',
            field=models.ForeignKey(blank=True, help_text='Diamond quality grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_diamond_lines', to='properties.diamondquality', verbose_name='Quality'),
        ),
        migrations.AddField(
            model_name='costcarddiamondline',
            name='rate_source',
            field=models.ForeignKey(blank=True, help_text='Diamond rate table row this line was originally copied from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_diamond_lines', to='properties.diamondstonerate', verbose_name='Rate Source'),
        ),
        migrations.AddField(
            model_name='costcarddiamondline',
            name='setting',
            field=models.ForeignKey(blank=True, help_text='Jewelry setting used for this diamond.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_diamond_lines', to='master.setting', verbose_name='Setting'),
        ),
        migrations.AddField(
            model_name='costcarddiamondline',
            name='shape',
            field=models.ForeignKey(blank=True, help_text='Diamond shape.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_diamond_lines', to='properties.diamondshape', verbose_name='Shape'),
        ),
        migrations.AddField(
            model_name='costcarddiamondline',
            name='stone',
            field=models.ForeignKey(blank=True, help_text='Diamond stone type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_diamond_lines', to='properties.diamondstone', verbose_name='Stone'),
        ),
        migrations.AddField(
            model_name='costcardfinishline',
            name='cost_card',
            field=models.ForeignKey(help_text='Cost card this finish line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='finish_lines', to='costcard.costcard', verbose_name='Cost Card'),
        ),
        migrations.AddField(
            model_name='costcardfinishline',
            name='finish_type',
            field=models.ForeignKey(help_text='Finish type applied to this piece.', on_delete=django.db.models.deletion.CASCADE, related_name='cost_card_finish_lines', to='master.finishtype', verbose_name='Finish Type'),
        ),
        migrations.AddIndex(
            model_name='stoneplace',
            index=models.Index(fields=['active'], name='costcard_st_active_7dcd16_idx'),
        ),
        migrations.AddField(
            model_name='costcarddiamondline',
            name='stone_place',
            field=models.ForeignKey(blank=True, help_text='Where this diamond is placed on the piece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_diamond_lines', to='costcard.stoneplace', verbose_name='Stone Place'),
        ),
        migrations.AddField(
            model_name='costcardcolorstoneline',
            name='stone_place',
            field=models.ForeignKey(blank=True, help_text='Where this color stone is placed on the piece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_card_colorstone_lines', to='costcard.stoneplace', verbose_name='Stone Place'),
        ),
        migrations.AddIndex(
            model_name='costcard',
            index=models.Index(fields=['active'], name='costcard_co_active_635eed_idx'),
        ),
        migrations.AddIndex(
            model_name='costcard',
            index=models.Index(fields=['our_style_no'], name='costcard_co_our_sty_114862_idx'),
        ),
        migrations.AddIndex(
            model_name='costcardfinishline',
            index=models.Index(fields=['active'], name='costcard_co_active_b7f475_idx'),
        ),
        migrations.AddConstraint(
            model_name='costcardfinishline',
            constraint=models.UniqueConstraint(fields=('cost_card', 'finish_type'), name='unique_cost_card_finish_type'),
        ),
        migrations.AddIndex(
            model_name='costcarddiamondline',
            index=models.Index(fields=['active'], name='costcard_co_active_dafdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='costcardcolorstoneline',
            index=models.Index(fields=['active'], name='costcard_co_active_94c78e_idx'),
        ),
    ]
