# Generated by Django 5.2.15 on 2026-09-11 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcard', '0004_alter_costcard_karat'),
        ('master', '0002_findingitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcard',
            name='finding_item',
            field=models.ForeignKey(blank=True, help_text='Finding item used on this piece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards', to='master.findingitem', verbose_name='Finding Item'),
        ),
    ]
