# Generated by Django 5.2.15 on 2026-09-11 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcard', '0005_costcard_finding_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcard',
            name='karat',
            field=models.PositiveIntegerField(blank=True, help_text='Karat value of the metal, e.g. 14, 18, 22, or 24.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kt'),
        ),
    ]
