# Generated by Django 5.2.15 on 2026-09-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcard', '0006_alter_costcard_karat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcardcolorstoneline',
            name='default_rate',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Yes if rate is found for stone, shape, and MM size; No for custom rate.', max_length=3, verbose_name='D.R.'),
        ),
        migrations.AlterField(
            model_name='costcarddiamondline',
            name='default_rate',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Yes if rate is found for stone, shape, and MM size; No for custom rate.', max_length=3, verbose_name='D.R.'),
        ),
    ]
