# Generated by Django 5.2.15 on 2026-09-19 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcard', '0008_alter_costcardcolorstoneline_default_rate_and_more'),
        ('master', '0008_remove_findingitem_type_alter_findingitem_metal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcard',
            name='finding_item',
            field=models.ForeignKey(blank=True, help_text='Finding type item used on this piece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards', to='master.findingitem', verbose_name='Finding Type'),
        ),
    ]
