# Generated by Django 5.2.15 on 2026-10-10 08:00

import costcard.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcard', '0009_alter_costcard_finding_item'),
        ('master', '0009_alter_acexecutive_code_alter_acexecutive_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcard',
            name='reference_style_no',
            field=models.CharField(blank=True, help_text='Reference style number for this costcard.', max_length=100, null=True, verbose_name='Reference Style No'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='back_view',
            field=models.ImageField(blank=True, help_text='Back view image of the costcard.', null=True, upload_to=costcard.models.back_view_image, verbose_name='Back View'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Jewelry category of this costcard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards', to='master.jewelrycategory', verbose_name='Jewelry Category'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='design_note',
            field=models.TextField(blank=True, help_text='Design instructions for this costcard.', null=True, verbose_name='Design Instruction'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='finding_item',
            field=models.ForeignKey(blank=True, help_text='Finding type item used on this costcard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards', to='master.findingitem', verbose_name='Finding Type'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='finding_type',
            field=models.ForeignKey(blank=True, help_text='Finding type used on this costcard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards', to='master.findingtype', verbose_name='Finding Type'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='fob',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Free-on-board amount for this costcard.', max_digits=15, verbose_name='F.O.B'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='front_view',
            field=models.ImageField(blank=True, help_text='Front view image of the costcard.', null=True, upload_to=costcard.models.front_view_image, verbose_name='Front View'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total gross weight of the costcard.', max_digits=10, null=True, verbose_name='Gross Weight'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='metal_purity',
            field=models.ForeignKey(blank=True, help_text='Metal purity grade used for this costcard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards', to='master.metalpurity', verbose_name='Metal Purity'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Net weight of the costcard excluding stones.', max_digits=10, null=True, verbose_name='Net Weight'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='side_view',
            field=models.ImageField(blank=True, help_text='Side view image of the costcard.', null=True, upload_to=costcard.models.side_view_image, verbose_name='Side View'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='special_note',
            field=models.TextField(blank=True, help_text='Special instructions for this costcard.', null=True, verbose_name='Special Instruction'),
        ),
        migrations.AlterField(
            model_name='costcard',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Jewelry sub-category of this costcard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_cards', to='master.jewelrysubcategory', verbose_name='Jewelry Sub Category'),
        ),
    ]
