# Generated by Django 5.2.15 on 2026-08-17 07:25

import InvenTree.fields
import InvenTree.validators
import common.currency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0080_company_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, help_text='City where the company is located.', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, help_text='Unique or internal code used to identify the company.', max_length=100, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, help_text='Country where the company is located.', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum credit limit allowed for the company.', max_digits=15, null=True, verbose_name='Credit Limit'),
        ),
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, help_text='Company fax number.', max_length=50, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating assigned to the company.', max_digits=5, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='company',
            name='ref_by',
            field=models.CharField(blank=True, help_text='Person or source that referred the company.', max_length=100, null=True, verbose_name='Ref By'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, help_text='State or province where the company is located.', max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile phone number of the contact person.', max_length=50, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(blank=True, help_text='Primary point of contact.', max_length=100, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(blank=True, default=common.currency.currency_code_default, help_text='Default currency used for this company.', max_length=3, validators=[InvenTree.validators.validate_currency_code], verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the company.', max_length=500, verbose_name='Company description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='link',
            field=InvenTree.fields.InvenTreeURLField(blank=True, help_text='Link to external company information.', max_length=2000, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Company name.', max_length=100, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number.', max_length=50, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Company Tax ID.', max_length=50, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=InvenTree.fields.InvenTreeURLField(blank=True, help_text='Company website URL.', max_length=2000, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the contact person.', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Name of the contact person.', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number of the contact person.', max_length=100, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, help_text='Designation or position of the contact person.', max_length=100, verbose_name='Role'),
        ),
    ]
