# Generated by Django 5.2.15 on 2026-08-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0081_company_city_company_code_company_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="default_stone_rate",
            field=models.BooleanField(
                default=False,
                help_text="Whether this company uses the default stone rate (maps to tbledger.defaultstonerate).",
                verbose_name="Default Stone Rate",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="group_id",
            field=models.IntegerField(
                blank=True,
                help_text="Group identifier for this company (maps to tbledger.groupid).",
                null=True,
                verbose_name="Group ID",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="lab_setting",
            field=models.BooleanField(
                default=False,
                help_text="Whether lab setting applies to this company (maps to tbledger.labsetting).",
                verbose_name="Lab Setting",
            ),
        ),
    ]
