# Generated by Django 5.2.15 on 2026-09-24 07:06

import InvenTree.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0082_company_default_stone_rate_company_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(help_text='City where the company is located.', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(help_text='Unique or internal code used to identify the company.', max_length=100, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(help_text='Primary point of contact.', max_length=100, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(help_text='Country where the company is located.', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, help_text='Maximum credit limit allowed for the company.', max_digits=15, verbose_name='Credit Limit'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(help_text='Description of the company.', max_length=500, verbose_name='Company description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(help_text='Contact email address.', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(help_text='Company fax number.', max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='company',
            name='link',
            field=InvenTree.fields.InvenTreeURLField(help_text='Link to external company information.', max_length=2000, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(help_text='Contact phone number.', max_length=50, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.DecimalField(decimal_places=2, help_text='Rating assigned to the company.', max_digits=5, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ref_by',
            field=models.CharField(help_text='Person or source that referred the company.', max_length=100, verbose_name='Ref By'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(help_text='State or province where the company is located.', max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(help_text='Company Tax ID.', max_length=50, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=InvenTree.fields.InvenTreeURLField(help_text='Company website URL.', max_length=2000, verbose_name='Website'),
        ),
    ]
