# Generated by Django 5.2.15 on 2026-09-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0083_alter_company_city_alter_company_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Email address of the contact person.', max_length=254, verbose_name='Email'),
        ),
    ]
