# Generated by Django 5.2.15 on 2026-08-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the color stone type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the color stone type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Color Stone',
                'verbose_name_plural': 'Color Stones',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_293711_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorStoneColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the color stone color.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the color stone color.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Color Stone Color',
                'verbose_name_plural': 'Color Stone Colors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_16febb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorStoneCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the color stone cut type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the color stone cut type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Color Stone Cut',
                'verbose_name_plural': 'Color Stone Cuts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_a9d24b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorStoneShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the color stone shape.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the color stone shape.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Color Stone Shape',
                'verbose_name_plural': 'Color Stone Shapes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_03ac8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorStoneSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the color stone size.', max_length=100, unique=True, verbose_name='Name')),
                ('mm_size', models.DecimalField(blank=True, decimal_places=3, help_text='Color stone size in millimeters.', max_digits=8, null=True, verbose_name='Size (mm)')),
                ('description', models.CharField(blank=True, help_text='Optional description of the color stone size.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Color Stone Size',
                'verbose_name_plural': 'Color Stone Sizes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_81b858_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiamondColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the diamond color grade.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the diamond color grade.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diamond Color',
                'verbose_name_plural': 'Diamond Colors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_0541c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiamondCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the diamond cut type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the diamond cut type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diamond Cut',
                'verbose_name_plural': 'Diamond Cuts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_28e980_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiamondQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the diamond quality grade.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the diamond quality grade.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diamond Quality',
                'verbose_name_plural': 'Diamond Qualities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_053e9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiamondShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the diamond shape.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the diamond shape.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diamond Shape',
                'verbose_name_plural': 'Diamond Shapes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_0ec0fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiamondSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the diamond size.', max_length=100, unique=True, verbose_name='Name')),
                ('mm_size', models.DecimalField(blank=True, decimal_places=3, help_text='Diamond size in millimeters.', max_digits=8, null=True, verbose_name='Size (mm)')),
                ('description', models.CharField(blank=True, help_text='Optional description of the diamond size.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diamond Size',
                'verbose_name_plural': 'Diamond Sizes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_b5b728_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiamondStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the diamond stone type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the diamond stone type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diamond Stone',
                'verbose_name_plural': 'Diamond Stones',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_0fc3bb_idx')],
            },
        ),
    ]
