# Generated by Django 5.2.15 on 2026-08-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the color stone type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the color stone type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Color Stone',
                'verbose_name_plural': 'Color Stones',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_293711_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorStoneColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the color stone color.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the color stone color.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Color Stone Color',
                'verbose_name_plural': 'Color Stone Colors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_16febb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorStoneCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the color stone cut type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the color stone cut type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Color Stone Cut',
                'verbose_name_plural': 'Color Stone Cuts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_a9d24b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorStoneQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the color stone quality grade.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the color stone quality grade.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Color Stone Quality',
                'verbose_name_plural': 'Color Stone Qualities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_9a6739_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorStoneShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the color stone shape.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the color stone shape.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Color Stone Shape',
                'verbose_name_plural': 'Color Stone Shapes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_03ac8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorStoneSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the color stone size.', max_length=100, unique=True, verbose_name='Name')),
                ('mm_size', models.DecimalField(blank=True, decimal_places=3, help_text='Color stone size in millimeters.', max_digits=8, null=True, verbose_name='Size (mm)')),
                ('description', models.CharField(blank=True, help_text='Optional description of the color stone size.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Color Stone Size',
                'verbose_name_plural': 'Color Stone Sizes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_81b858_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiamondColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the diamond color grade.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the diamond color grade.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diamond Color',
                'verbose_name_plural': 'Diamond Colors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_0541c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiamondCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the diamond cut type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the diamond cut type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diamond Cut',
                'verbose_name_plural': 'Diamond Cuts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_28e980_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiamondQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the diamond quality grade.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the diamond quality grade.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diamond Quality',
                'verbose_name_plural': 'Diamond Qualities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_053e9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiamondShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the diamond shape.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the diamond shape.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diamond Shape',
                'verbose_name_plural': 'Diamond Shapes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_0ec0fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiamondSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the diamond size.', max_length=100, unique=True, verbose_name='Name')),
                ('mm_size', models.DecimalField(blank=True, decimal_places=3, help_text='Diamond size in millimeters.', max_digits=8, null=True, verbose_name='Size (mm)')),
                ('description', models.CharField(blank=True, help_text='Optional description of the diamond size.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diamond Size',
                'verbose_name_plural': 'Diamond Sizes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_b5b728_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiamondStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the diamond stone type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the diamond stone type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Diamond Stone',
                'verbose_name_plural': 'Diamond Stones',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_0fc3bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorStoneRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('pointer', models.DecimalField(blank=True, decimal_places=4, help_text='Pointer value for rate lookup.', max_digits=10, null=True, verbose_name='Pointer')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Rate per piece or per carat.', max_digits=10, verbose_name='Rate')),
                ('pc', models.CharField(choices=[('P', 'Per Piece'), ('C', 'Per Carat')], default='C', help_text='Rate unit: P = Per Piece, C = Per Carat.', max_length=1, verbose_name='P/C')),
                ('customer_id', models.IntegerField(blank=True, help_text='Optional customer-specific rate override.', null=True, verbose_name='Customer ID')),
                ('color', models.ForeignKey(blank=True, help_text='Color stone color.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.colorstonecolor', verbose_name='Color')),
                ('cut', models.ForeignKey(blank=True, help_text='Color stone cut type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.colorstonecut', verbose_name='Cut')),
                ('quality', models.ForeignKey(blank=True, help_text='Color stone quality grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.colorstonequality', verbose_name='Quality')),
                ('stone', models.ForeignKey(blank=True, help_text='Color stone type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.colorstone', verbose_name='Stone')),
                ('shape', models.ForeignKey(blank=True, help_text='Color stone shape.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.colorstoneshape', verbose_name='Shape')),
                ('mm_size', models.ForeignKey(blank=True, help_text='Color stone size.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.colorstonesize', verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Color Stone Rate',
                'verbose_name_plural': 'Color Stone Rates',
                'ordering': ['shape', 'mm_size', 'pointer'],
                'indexes': [models.Index(fields=['active'], name='properties__active_f86c47_idx'), models.Index(fields=['shape', 'mm_size', 'pointer'], name='properties__shape_i_f42e80_idx')],
                'unique_together': {('shape', 'mm_size', 'stone', 'color', 'cut', 'quality', 'pointer', 'customer_id')},
            },
        ),
        migrations.CreateModel(
            name='DiamondStoneRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('pointer', models.DecimalField(blank=True, decimal_places=4, help_text='Pointer value for rate lookup.', max_digits=10, null=True, verbose_name='Pointer')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Rate per piece or per carat.', max_digits=10, verbose_name='Rate')),
                ('pc', models.CharField(choices=[('P', 'Per Piece'), ('C', 'Per Carat')], default='C', help_text='Rate unit: P = Per Piece, C = Per Carat.', max_length=1, verbose_name='P/C')),
                ('customer_id', models.IntegerField(blank=True, help_text='Optional customer-specific rate override.', null=True, verbose_name='Customer ID')),
                ('color', models.ForeignKey(blank=True, help_text='Diamond color grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.diamondcolor', verbose_name='Color')),
                ('cut', models.ForeignKey(blank=True, help_text='Diamond cut type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.diamondcut', verbose_name='Cut')),
                ('mm_size', models.ForeignKey(blank=True, help_text='Diamond size.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.diamondsize', verbose_name='Size')),
                ('quality', models.ForeignKey(blank=True, help_text='Diamond quality grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.diamondquality', verbose_name='Quality')),
                ('shape', models.ForeignKey(blank=True, help_text='Diamond shape.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.diamondshape', verbose_name='Shape')),
                ('stone', models.ForeignKey(blank=True, help_text='Diamond stone type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.diamondstone', verbose_name='Stone')),
            ],
            options={
                'verbose_name': 'Diamond Stone Rate',
                'verbose_name_plural': 'Diamond Stone Rates',
                'ordering': ['shape', 'mm_size', 'pointer'],
                'indexes': [models.Index(fields=['active'], name='properties__active_1c954a_idx'), models.Index(fields=['shape', 'mm_size', 'pointer'], name='properties__shape_i_ef6333_idx')],
                'unique_together': {('shape', 'mm_size', 'stone', 'color', 'cut', 'quality', 'pointer', 'customer_id')},
            },
        ),
    ]
