# Generated by Django 5.2.15 on 2026-09-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamondsize',
            name='sieve_size',
            field=models.CharField(
                blank=True,
                help_text='Sieve size corresponding to this diamond size.',
                max_length=50,
                null=True,
                verbose_name='Sieve Size',
            ),
        ),
    ]
