# Generated by Django 5.2.15 on 2026-09-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0082_company_default_stone_rate_company_group_id_and_more'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='colorstonerate',
            constraint=models.UniqueConstraint(fields=('shape', 'mm_size', 'stone'), name='uniq_color_stone_rate'),
        ),
        migrations.AddConstraint(
            model_name='diamondstonerate',
            constraint=models.UniqueConstraint(fields=('shape', 'mm_size', 'stone'), name='uniq_diamond_stone_rate'),
        ),
    ]
