# Generated by Django 5.2.15 on 2026-08-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorStoneQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the color stone quality grade.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the color stone quality grade.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Color Stone Quality',
                'verbose_name_plural': 'Color Stone Qualities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='properties__active_9a6739_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColorStoneRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('pointer', models.DecimalField(blank=True, decimal_places=4, help_text='Pointer value for rate lookup.', max_digits=10, null=True, verbose_name='Pointer')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Rate per piece or per carat.', max_digits=10, verbose_name='Rate')),
                ('pc', models.CharField(choices=[('P', 'Per Piece'), ('C', 'Per Carat')], default='C', help_text='Rate unit: P = Per Piece, C = Per Carat.', max_length=1, verbose_name='P/C')),
                ('customer_id', models.IntegerField(blank=True, help_text='Optional customer-specific rate override.', null=True, verbose_name='Customer ID')),
                ('color', models.ForeignKey(blank=True, help_text='Color stone color.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.colorstonecolor', verbose_name='Color')),
                ('cut', models.ForeignKey(blank=True, help_text='Color stone cut type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.colorstonecut', verbose_name='Cut')),
                ('mm_size', models.ForeignKey(blank=True, help_text='Color stone size.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.colorstonesize', verbose_name='Size')),
                ('quality', models.ForeignKey(blank=True, help_text='Color stone quality grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.colorstonequality', verbose_name='Quality')),
                ('shape', models.ForeignKey(blank=True, help_text='Color stone shape.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.colorstoneshape', verbose_name='Shape')),
                ('stone', models.ForeignKey(blank=True, help_text='Color stone type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.colorstone', verbose_name='Stone')),
            ],
            options={
                'verbose_name': 'Color Stone Rate',
                'verbose_name_plural': 'Color Stone Rates',
                'ordering': ['shape', 'mm_size', 'pointer'],
                'indexes': [models.Index(fields=['active'], name='properties__active_f86c47_idx'), models.Index(fields=['shape', 'mm_size', 'pointer'], name='properties__shape_i_f42e80_idx')],
                'unique_together': {('shape', 'mm_size', 'stone', 'color', 'cut', 'quality', 'pointer', 'customer_id')},
            },
        ),
        migrations.CreateModel(
            name='DiamondStoneRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('pointer', models.DecimalField(blank=True, decimal_places=4, help_text='Pointer value for rate lookup.', max_digits=10, null=True, verbose_name='Pointer')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Rate per piece or per carat.', max_digits=10, verbose_name='Rate')),
                ('pc', models.CharField(choices=[('P', 'Per Piece'), ('C', 'Per Carat')], default='C', help_text='Rate unit: P = Per Piece, C = Per Carat.', max_length=1, verbose_name='P/C')),
                ('customer_id', models.IntegerField(blank=True, help_text='Optional customer-specific rate override.', null=True, verbose_name='Customer ID')),
                ('color', models.ForeignKey(blank=True, help_text='Diamond color grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.diamondcolor', verbose_name='Color')),
                ('cut', models.ForeignKey(blank=True, help_text='Diamond cut type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.diamondcut', verbose_name='Cut')),
                ('mm_size', models.ForeignKey(blank=True, help_text='Diamond size.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.diamondsize', verbose_name='Size')),
                ('quality', models.ForeignKey(blank=True, help_text='Diamond quality grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.diamondquality', verbose_name='Quality')),
                ('shape', models.ForeignKey(blank=True, help_text='Diamond shape.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.diamondshape', verbose_name='Shape')),
                ('stone', models.ForeignKey(blank=True, help_text='Diamond stone type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='properties.diamondstone', verbose_name='Stone')),
            ],
            options={
                'verbose_name': 'Diamond Stone Rate',
                'verbose_name_plural': 'Diamond Stone Rates',
                'ordering': ['shape', 'mm_size', 'pointer'],
                'indexes': [models.Index(fields=['active'], name='properties__active_1c954a_idx'), models.Index(fields=['shape', 'mm_size', 'pointer'], name='properties__shape_i_ef6333_idx')],
                'unique_together': {('shape', 'mm_size', 'stone', 'color', 'cut', 'quality', 'pointer', 'customer_id')},
            },
        ),
    ]
