# Generated by Django 5.2.15 on 2026-10-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_colorstonerate_uniq_color_stone_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorstone',
            name='name',
            field=models.CharField(help_text='Name of the color stone type.', max_length=100, unique=True, verbose_name='Stone'),
        ),
        migrations.AlterField(
            model_name='colorstonecolor',
            name='name',
            field=models.CharField(help_text='Name of the color stone color.', max_length=100, unique=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='colorstonecut',
            name='name',
            field=models.CharField(help_text='Name of the color stone cut type.', max_length=100, unique=True, verbose_name='Cut'),
        ),
        migrations.AlterField(
            model_name='colorstonequality',
            name='name',
            field=models.CharField(help_text='Name of the color stone quality grade.', max_length=100, unique=True, verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='colorstoneshape',
            name='name',
            field=models.CharField(help_text='Name of the color stone shape.', max_length=100, unique=True, verbose_name='Shape'),
        ),
        migrations.AlterField(
            model_name='colorstonesize',
            name='name',
            field=models.CharField(help_text='Name of the color stone size.', max_length=100, unique=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='diamondcolor',
            name='name',
            field=models.CharField(help_text='Name of the diamond color grade.', max_length=100, unique=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='diamondcut',
            name='name',
            field=models.CharField(help_text='Name of the diamond cut type.', max_length=100, unique=True, verbose_name='Cut'),
        ),
        migrations.AlterField(
            model_name='diamondquality',
            name='name',
            field=models.CharField(help_text='Name of the diamond quality grade.', max_length=100, unique=True, verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='diamondshape',
            name='name',
            field=models.CharField(help_text='Name of the diamond shape.', max_length=100, unique=True, verbose_name='Shape'),
        ),
        migrations.AlterField(
            model_name='diamondsize',
            name='name',
            field=models.CharField(help_text='Name of the diamond size.', max_length=100, unique=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='diamondstone',
            name='name',
            field=models.CharField(help_text='Name of the diamond stone type.', max_length=100, unique=True, verbose_name='Stone'),
        ),
    ]
