# Generated by Django 5.2.15 on 2026-09-02 09:15

from django.db import migrations, models


def copy_legacy_customer_ids(apps, schema_editor):
    """Map old integer customer_id values onto the new Company M2M."""
    Company = apps.get_model('company', 'Company')
    for model_name in ('DiamondStoneRate', 'ColorStoneRate'):
        Rate = apps.get_model('properties', model_name)
        for rate in Rate.objects.exclude(customer_id__isnull=True):
            company = Company.objects.filter(pk=rate.customer_id).first()
            if company:
                rate.customers.add(company)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0082_company_default_stone_rate_company_group_id_and_more'),
        ('properties', '0002_diamondsize_sieve_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colorstonerate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='diamondstonerate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='colorstonerate',
            name='all_customers',
            field=models.BooleanField(
                default=False,
                help_text='If set, this rate applies to every customer (Select All Customers).',
                verbose_name='All Customers',
            ),
        ),
        migrations.AddField(
            model_name='diamondstonerate',
            name='all_customers',
            field=models.BooleanField(
                default=False,
                help_text='If set, this rate applies to every customer (Select All Customers).',
                verbose_name='All Customers',
            ),
        ),
        migrations.AddField(
            model_name='colorstonerate',
            name='customers',
            field=models.ManyToManyField(
                blank=True,
                help_text='Customers this rate applies to. Leave empty when All Customers is selected.',
                limit_choices_to={'is_customer': True},
                related_name='color_stone_rates',
                to='company.company',
                verbose_name='Customers',
            ),
        ),
        migrations.AddField(
            model_name='diamondstonerate',
            name='customers',
            field=models.ManyToManyField(
                blank=True,
                help_text='Customers this rate applies to. Leave empty when All Customers is selected.',
                limit_choices_to={'is_customer': True},
                related_name='diamond_stone_rates',
                to='company.company',
                verbose_name='Customers',
            ),
        ),
        migrations.RunPython(copy_legacy_customer_ids, noop_reverse),
        migrations.RemoveField(
            model_name='colorstonerate',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='diamondstonerate',
            name='customer_id',
        ),
        migrations.AddIndex(
            model_name='colorstonerate',
            index=models.Index(fields=['all_customers'], name='properties__all_cus_color_idx'),
        ),
        migrations.AddIndex(
            model_name='diamondstonerate',
            index=models.Index(fields=['all_customers'], name='properties__all_cus_dia_idx'),
        ),
    ]
