# Generated by Django 5.2.15 on 2026-09-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_size_mm_size_charfield'),
        ('properties', '0005_rename_properties__all_cus_color_idx_properties__all_cus_58b106_idx_and_more'),
    ]

    operations = [
    ]
