# Generated by Django 5.2.15 on 2026-09-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_size_mm_size_charfield'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='colorstonerate',
            new_name='properties__all_cus_58b106_idx',
            old_name='properties__all_cus_color_idx',
        ),
        migrations.RenameIndex(
            model_name='diamondstonerate',
            new_name='properties__all_cus_90e46b_idx',
            old_name='properties__all_cus_dia_idx',
        ),
    ]
