# Generated by Django 5.2.15 on 2026-09-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_merge_20260903_1227'),
        ('properties', '0006_rename_properties__all_cus_color_idx_properties__all_cus_58b106_idx_and_more'),
    ]

    operations = [
    ]
