# Generated by Django 5.2.15 on 2026-08-10 08:48

import django.core.validators
import django.db.models.deletion
import master.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the accounts executive.', max_length=100, verbose_name='Name')),
                ('code', models.CharField(blank=True, help_text='Optional code used to identify the accounts executive.', max_length=50, null=True, verbose_name='Code')),
                ('email', models.EmailField(blank=True, help_text='Email address of the accounts executive.', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number of the accounts executive.', max_length=50, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'A/C Executive',
                'verbose_name_plural': 'A/C Executives',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourierService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the courier or shipping service.', max_length=100, unique=True, verbose_name='Name')),
                ('contact_person', models.CharField(blank=True, help_text='Name of the primary contact person.', max_length=100, null=True, verbose_name='Contact Person')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number for the courier service.', max_length=50, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, help_text='Email address for the courier service.', max_length=254, null=True, verbose_name='Email')),
                ('tracking_url', models.URLField(blank=True, help_text='URL used to track shipments from this courier service.', max_length=500, null=True, verbose_name='Tracking URL')),
            ],
            options={
                'verbose_name': 'Courier Service',
                'verbose_name_plural': 'Courier Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FindingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the jewelry finding type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the finding type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Finding Type',
                'verbose_name_plural': 'Finding Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the surface finish type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the finish type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Finish Type',
                'verbose_name_plural': 'Finish Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('code', models.CharField(help_text='Unique code used to identify the metal type.', max_length=100, null=True, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Name of the metal type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the metal type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Metal Type',
                'verbose_name_plural': 'Metal Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the hallmark or stamp.', max_length=100, unique=True, verbose_name='Name')),
                ('image', models.ImageField(help_text='Image representing the hallmark or stamp.', upload_to=master.models.stamp_image, verbose_name='Image')),
                ('description', models.CharField(blank=True, help_text='Optional description of the stamp.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Stamp',
                'verbose_name_plural': 'Stamps',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the payment terms.', max_length=100, unique=True, verbose_name='Name')),
                ('days', models.PositiveIntegerField(default=0, help_text='Number of days allowed under these payment terms.', verbose_name='Days')),
                ('description', models.CharField(blank=True, help_text='Optional description of the payment terms.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Terms',
                'verbose_name_plural': 'Terms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('duty', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Duty percentage applicable to the selected metal type.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Duty')),
                ('markup', models.PositiveIntegerField(default=0, help_text='Markup value applicable to the selected metal type.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Markup')),
                ('description', models.CharField(blank=True, help_text='Optional description of the duty configuration.', max_length=250, null=True, verbose_name='Description')),
                ('metal_type', models.ForeignKey(help_text='Metal type for which this duty applies.', on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='master.metaltype', verbose_name='Metal Type')),
            ],
            options={
                'verbose_name': 'Duty',
                'verbose_name_plural': 'Duties',
                'ordering': ['metal_type'],
            },
        ),
        migrations.CreateModel(
            name='MetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Metal rate applicable for the selected date.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rate')),
                ('date', models.DateField(help_text='Date on which this metal rate is applicable.', verbose_name='Date')),
                ('metal_type', models.ForeignKey(help_text='Metal type for which this rate applies.', on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='master.metaltype', verbose_name='Metal Type')),
            ],
            options={
                'verbose_name': 'Metal Rate',
                'verbose_name_plural': 'Metal Rates',
                'ordering': ['-date', 'metal_type'],
                'constraints': [models.UniqueConstraint(fields=('metal_type', 'date'), name='unique_metal_rate_per_day')],
            },
        ),
        migrations.CreateModel(
            name='MetalPurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the metal purity grade.', max_length=50, verbose_name='Name')),
                ('purity', models.DecimalField(decimal_places=2, help_text='Purity percentage of the metal, from 0 to 100.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Purity (%)')),
                ('metal_type', models.ForeignKey(help_text='Metal type associated with this purity grade.', on_delete=django.db.models.deletion.CASCADE, related_name='purities', to='master.metaltype', verbose_name='Metal Type')),
            ],
            options={
                'verbose_name': 'Metal Purity',
                'verbose_name_plural': 'Metal Purities',
                'ordering': ['metal_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('metal_type', 'name'), name='unique_metal_type_purity_name')],
            },
        ),
    ]
