# Generated by Django 5.2.15 on 2026-08-18 12:14

import django.core.validators
import django.db.models.deletion
import master.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the accounts executive.', max_length=100, verbose_name='Name')),
                ('code', models.CharField(blank=True, help_text='Optional code used to identify the accounts executive.', max_length=50, null=True, verbose_name='Code')),
                ('email', models.EmailField(blank=True, help_text='Email address of the accounts executive.', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number of the accounts executive.', max_length=50, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'A/C Executive',
                'verbose_name_plural': 'A/C Executives',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='master_acex_name_f2a3d3_idx'), models.Index(fields=['active'], name='master_acex_active_073636_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourierService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the courier or shipping service.', max_length=100, unique=True, verbose_name='Name')),
                ('contact_person', models.CharField(blank=True, help_text='Name of the primary contact person.', max_length=100, null=True, verbose_name='Contact Person')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number for the courier service.', max_length=50, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, help_text='Email address for the courier service.', max_length=254, null=True, verbose_name='Email')),
                ('tracking_url', models.URLField(blank=True, help_text='URL used to track shipments from this courier service.', max_length=500, null=True, verbose_name='Tracking URL')),
            ],
            options={
                'verbose_name': 'Courier Service',
                'verbose_name_plural': 'Courier Services',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_cour_active_ed34c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FindingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the jewelry finding type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the finding type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Finding Type',
                'verbose_name_plural': 'Finding Types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_find_active_9e7527_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the surface finish type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the finish type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Finish Type',
                'verbose_name_plural': 'Finish Types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_fini_active_9c4df2_idx')],
            },
        ),
        migrations.CreateModel(
            name='JewelryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the jewelry category.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the jewelry category.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Jewelry Category',
                'verbose_name_plural': 'Jewelry Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_jewe_active_b5ad35_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('code', models.CharField(help_text='Unique code used to identify the metal type.', max_length=100, null=True, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Name of the metal type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the metal type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Metal Type',
                'verbose_name_plural': 'Metal Types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_meta_active_ed3f3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the jewelry setting type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the jewelry setting type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_sett_active_d729f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the hallmark or stamp.', max_length=100, unique=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, help_text='Optional image representing the hallmark or stamp.', null=True, upload_to=master.models.stamp_image, verbose_name='Image')),
                ('description', models.CharField(blank=True, help_text='Optional description of the stamp.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Stamp',
                'verbose_name_plural': 'Stamps',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_stam_active_36a5ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the template.', max_length=150, verbose_name='Name')),
                ('subject', models.CharField(blank=True, help_text='Email subject line to use with this template.', max_length=255, null=True, verbose_name='Subject')),
                ('template', models.TextField(blank=True, help_text='Template content — inline HTML/code, or a path/reference to a report template.', null=True, verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_temp_active_474d3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the payment terms.', max_length=100, unique=True, verbose_name='Name')),
                ('days', models.PositiveIntegerField(default=0, help_text='Number of days allowed under these payment terms.', verbose_name='Days')),
                ('description', models.CharField(blank=True, help_text='Optional description of the payment terms.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Terms',
                'verbose_name_plural': 'Terms',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_term_active_b796b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='JewelrySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the jewelry sub-category.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the jewelry sub-category.', max_length=250, null=True, verbose_name='Description')),
                ('category', models.ForeignKey(help_text='Jewelry category associated with this sub-category.', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='master.jewelrycategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Jewelry Sub Category',
                'verbose_name_plural': 'Jewelry Sub Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_jewe_active_f43d4f_idx'), models.Index(fields=['category'], name='master_jewe_categor_770326_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Metal rate applicable for the selected date.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rate')),
                ('date', models.DateField(help_text='Date on which this metal rate is applicable.', verbose_name='Date')),
                ('metal_type', models.ForeignKey(help_text='Metal type for which this rate applies.', on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='master.metaltype', verbose_name='Metal Type')),
            ],
            options={
                'verbose_name': 'Metal Rate',
                'verbose_name_plural': 'Metal Rates',
                'ordering': ['-date', 'metal_type'],
                'indexes': [models.Index(fields=['date'], name='master_meta_date_e15a96_idx'), models.Index(fields=['active'], name='master_meta_active_7036f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('metal_type', 'date'), name='unique_metal_rate_per_day')],
            },
        ),
        migrations.CreateModel(
            name='MetalPurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the metal purity grade.', max_length=50, verbose_name='Name')),
                ('purity', models.DecimalField(decimal_places=2, help_text='Purity percentage of the metal, from 0 to 100.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Purity (%)')),
                ('metal_type', models.ForeignKey(help_text='Metal type associated with this purity grade.', on_delete=django.db.models.deletion.CASCADE, related_name='purities', to='master.metaltype', verbose_name='Metal Type')),
            ],
            options={
                'verbose_name': 'Metal Purity',
                'verbose_name_plural': 'Metal Purities',
                'ordering': ['metal_type', 'name'],
                'indexes': [models.Index(fields=['active'], name='master_meta_active_4342c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('metal_type', 'name'), name='unique_metal_type_purity_name')],
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('duty', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Duty percentage applicable to the selected metal type.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Duty')),
                ('markup', models.PositiveIntegerField(default=0, help_text='Markup value applicable to the selected metal type.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Markup')),
                ('description', models.CharField(blank=True, help_text='Optional description of the duty configuration.', max_length=250, null=True, verbose_name='Description')),
                ('metal_type', models.ForeignKey(help_text='Metal type for which this duty applies.', on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='master.metaltype', verbose_name='Metal Type')),
            ],
            options={
                'verbose_name': 'Duty',
                'verbose_name_plural': 'Duties',
                'ordering': ['metal_type'],
                'indexes': [models.Index(fields=['active'], name='master_duty_active_afb011_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabourSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the labour setting.', max_length=100, verbose_name='Name')),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed'), ('per_gram', 'Per Gram'), ('per_piece', 'Per Piece'), ('percentage', 'Percentage')], default='fixed', help_text='Method used to calculate the labour charge.', max_length=20, verbose_name='Charge Type')),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Labour charge rate based on the selected charge type.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rate')),
                ('setting', models.ForeignKey(blank=True, help_text='Jewelry setting associated with this labour configuration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_settings', to='master.setting', verbose_name='Setting')),
            ],
            options={
                'verbose_name': 'Labour Setting',
                'verbose_name_plural': 'Labour Settings',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_labo_active_485605_idx')],
            },
        ),
        migrations.CreateModel(
            name='POMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the P.O. Mail configuration.', max_length=150, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this configuration.', verbose_name='Order')),
                ('format1', models.OneToOneField(blank=True, help_text='Template used for Vendor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format1', to='master.templates', verbose_name='Format 1')),
                ('format2', models.OneToOneField(blank=True, help_text='Template used for Diamond Office.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format2', to='master.templates', verbose_name='Format 2')),
                ('format3', models.OneToOneField(blank=True, help_text='Template used for Color Stone Office.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format3', to='master.templates', verbose_name='Format 3')),
                ('format4', models.OneToOneField(blank=True, help_text='Template used for New York Office.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format4', to='master.templates', verbose_name='Format 4')),
            ],
            options={
                'verbose_name': 'P.O. Mail',
                'verbose_name_plural': 'P.O. Mails',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['active'], name='master_poma_active_3e0d36_idx')],
            },
        ),
    ]
