# Generated by Django 5.2.15 on 2026-08-31 16:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0081_company_city_company_code_company_country_and_more'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingtype',
            name='metal',
            field=models.CharField(blank=True, help_text='Metal of the finding, e.g. 14 KT Gold.', max_length=100, null=True, verbose_name='Finding Metal'),
        ),
        migrations.AddField(
            model_name='findingtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Price of the finding.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Finding Price'),
        ),
        migrations.AddField(
            model_name='findingtype',
            name='type',
            field=models.CharField(blank=True, help_text='Type or specification of the finding, e.g. CABLE - 30.', max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='findingtype',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Weight of the finding in grams.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Finding Wt.'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='customers',
            field=models.ManyToManyField(blank=True, help_text='Customers assigned to this stamp.', related_name='stamps', to='company.company', verbose_name='Customers'),
        ),
        migrations.AddField(
            model_name='terms',
            name='vendors',
            field=models.ManyToManyField(blank=True, help_text='Vendors to whom these payment terms apply.', related_name='payment_terms', to='company.company', verbose_name='Vendors'),
        ),
        migrations.AlterField(
            model_name='findingtype',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description of the finding.', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='findingtype',
            name='name',
            field=models.CharField(help_text='Name of the jewelry finding item.', max_length=100, unique=True, verbose_name='Finding Item'),
        ),
        migrations.AlterField(
            model_name='jewelrysubcategory',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional jewelry category associated with this sub-category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='master.jewelrycategory', verbose_name='Category'),
        ),
        migrations.AddIndex(
            model_name='findingtype',
            index=models.Index(fields=['name'], name='master_find_name_6df9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='findingtype',
            index=models.Index(fields=['type'], name='master_find_type_842e4f_idx'),
        ),
    ]
