# Generated by Django 5.2.15 on 2026-09-11 05:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(max_length=100, verbose_name='Finding Item')),
                ('type', models.CharField(blank=True, help_text='Type or specification of the finding, e.g. CABLE - 30.', max_length=100, null=True, verbose_name='Type')),
                ('weight', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Weight of the finding in grams.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Finding Wt.')),
                ('metal', models.CharField(blank=True, help_text='Metal of the finding, e.g. 14 KT Gold.', max_length=100, null=True, verbose_name='Finding Metal')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Price of the finding.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Finding Price')),
            ],
            options={
                'verbose_name': 'Finding Item',
                'verbose_name_plural': 'Finding Items',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='findingtype',
            name='master_find_type_842e4f_idx',
        ),
        migrations.RemoveField(
            model_name='findingtype',
            name='metal',
        ),
        migrations.RemoveField(
            model_name='findingtype',
            name='price',
        ),
        migrations.RemoveField(
            model_name='findingtype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='findingtype',
            name='weight',
        ),
        migrations.AlterField(
            model_name='findingtype',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description of the finding type.', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='findingtype',
            name='name',
            field=models.CharField(help_text='Name of the jewelry finding type.', max_length=100, unique=True, verbose_name='Finding Type'),
        ),
        migrations.AddField(
            model_name='findingitem',
            name='finding_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='master.findingtype', verbose_name='Finding Type'),
        ),
        migrations.AddIndex(
            model_name='findingitem',
            index=models.Index(fields=['finding_type'], name='master_find_finding_b1d3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='findingitem',
            index=models.Index(fields=['name'], name='master_find_name_adc5db_idx'),
        ),
        migrations.AddIndex(
            model_name='findingitem',
            index=models.Index(fields=['active'], name='master_find_active_000d1f_idx'),
        ),
    ]
