# Generated by Django 5.2.15 on 2026-08-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='acexecutive',
            index=models.Index(fields=['name'], name='master_acex_name_f2a3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='acexecutive',
            index=models.Index(fields=['active'], name='master_acex_active_073636_idx'),
        ),
        migrations.AddIndex(
            model_name='courierservice',
            index=models.Index(fields=['active'], name='master_cour_active_ed34c3_idx'),
        ),
        migrations.AddIndex(
            model_name='duty',
            index=models.Index(fields=['active'], name='master_duty_active_afb011_idx'),
        ),
        migrations.AddIndex(
            model_name='findingtype',
            index=models.Index(fields=['active'], name='master_find_active_9e7527_idx'),
        ),
        migrations.AddIndex(
            model_name='finishtype',
            index=models.Index(fields=['active'], name='master_fini_active_9c4df2_idx'),
        ),
        migrations.AddIndex(
            model_name='metalpurity',
            index=models.Index(fields=['active'], name='master_meta_active_4342c9_idx'),
        ),
        migrations.AddIndex(
            model_name='metalrate',
            index=models.Index(fields=['date'], name='master_meta_date_e15a96_idx'),
        ),
        migrations.AddIndex(
            model_name='metalrate',
            index=models.Index(fields=['active'], name='master_meta_active_7036f6_idx'),
        ),
        migrations.AddIndex(
            model_name='metaltype',
            index=models.Index(fields=['active'], name='master_meta_active_ed3f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='stamp',
            index=models.Index(fields=['active'], name='master_stam_active_36a5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='terms',
            index=models.Index(fields=['active'], name='master_term_active_b796b8_idx'),
        ),
    ]
