# Generated by Django 5.2.15 on 2026-09-11 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_findingitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalpurity',
            name='purity',
            field=models.PositiveIntegerField(help_text='Karat value of the metal, such as 14, 18, 22.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Karat'),
        ),
    ]
