# Generated by Django 5.2.15 on 2026-08-12 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_acexecutive_master_acex_name_f2a3d3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Metal rate applicable for the selected date.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rate'),
        ),
    ]
