# Generated by Django 5.2.15 on 2026-08-14 12:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_metalrate_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the jewelry setting type.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the jewelry setting type.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_sett_active_d729f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabourSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the labour setting.', max_length=100, verbose_name='Name')),
                ('charge_type', models.CharField(choices=[('fixed', 'Fixed'), ('per_gram', 'Per Gram'), ('per_piece', 'Per Piece'), ('percentage', 'Percentage')], default='fixed', help_text='Method used to calculate the labour charge.', max_length=20, verbose_name='Charge Type')),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Labour charge rate based on the selected charge type.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rate')),
                ('setting', models.ForeignKey(blank=True, help_text='Jewelry setting associated with this labour configuration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_settings', to='master.setting', verbose_name='Setting')),
            ],
            options={
                'verbose_name': 'Labour Setting',
                'verbose_name_plural': 'Labour Settings',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_labo_active_485605_idx')],
            },
        ),
    ]
