# Generated by Django 5.2.15 on 2026-09-11 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_metalpurity_purity'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalpurity',
            name='karat',
            field=models.CharField(blank=True, help_text='Karat value of the metal, e.g. 14KT, 18KT.', max_length=20, null=True, verbose_name='Kt'),
        ),
        migrations.AlterField(
            model_name='metalpurity',
            name='purity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purity percentage of the metal, from 0 to 100.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Purity (%)'),
        ),
    ]
