# Generated by Django 5.2.15 on 2026-08-14 09:25

from django.db import migrations

def create_triggers(apps, schema_editor):
    app_config = apps.get_app_config('master')
    # Check karega ki database PostgreSQL hai ya SQLite
    db_engine = schema_editor.connection.vendor

    with schema_editor.connection.cursor() as cursor:
        
        # --- AGAR POSTGRESQL HAI ---
        if db_engine == 'postgresql':
            # 1. Pehle shared function banayein
            cursor.execute("""
                CREATE OR REPLACE FUNCTION update_modified_column()
                RETURNS TRIGGER AS $$
                BEGIN
                    NEW.updated_at = NOW();
                    RETURN NEW;
                END;
                $$ language 'plpgsql';
            """)
            
            # 2. Saari tables par trigger lagayein
            for model in app_config.get_models():
                table_name = model._meta.db_table
                trigger_name = f"trig_update_timestamp_{table_name}"
                cursor.execute(f"""
                    CREATE TRIGGER {trigger_name}
                    BEFORE UPDATE ON {table_name}
                    FOR EACH ROW
                    EXECUTE FUNCTION update_modified_column();
                """)

        # --- AGAR SQLITE HAI ---
        elif db_engine == 'sqlite':
            for model in app_config.get_models():
                table_name = model._meta.db_table
                trigger_name = f"trig_update_timestamp_{table_name}"
                
                # SQLite ke liye AFTER UPDATE trigger
                cursor.execute(f"""
                    CREATE TRIGGER IF NOT EXISTS {trigger_name}
                    AFTER UPDATE ON {table_name}
                    BEGIN
                        UPDATE {table_name}
                        SET updated_at = STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')
                        WHERE id = NEW.id;
                    END;
                """)

def remove_triggers(apps, schema_editor):
    app_config = apps.get_app_config('master')
    db_engine = schema_editor.connection.vendor

    with schema_editor.connection.cursor() as cursor:
        for model in app_config.get_models():
            table_name = model._meta.db_table
            trigger_name = f"trig_update_timestamp_{table_name}"
            
            cursor.execute(f"DROP TRIGGER IF EXISTS {trigger_name} ON {table_name};")
            
        if db_engine == 'postgresql':
            cursor.execute("DROP FUNCTION IF EXISTS update_modified_column();")


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_metalrate_rate'),
    ]

    operations = [
        migrations.RunPython(create_triggers, reverse_code=remove_triggers),
    ]