# Generated by Django 5.2.15 on 2026-08-17 10:08

import master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_findingtype_metal_findingtype_price_findingtype_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image representing the hallmark or stamp.', null=True, upload_to=master.models.stamp_image, verbose_name='Image'),
        ),
    ]
