# Generated by Django 5.2.15 on 2026-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_stamp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='all_customers',
            field=models.BooleanField(default=False, help_text='If set, this rate applies to every customer (Select All Customers).', verbose_name='All Customers'),
        ),
        migrations.AddField(
            model_name='terms',
            name='all_vendors',
            field=models.BooleanField(default=False, help_text='If set, these terms apply to every vendor (Select All Vendors).', verbose_name='All Vendors'),
        ),
    ]
