# Generated by Django 5.2.15 on 2026-08-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_stamp_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the jewelry category.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the jewelry category.', max_length=250, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Jewelry Category',
                'verbose_name_plural': 'Jewelry Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_jewe_active_b5ad35_idx')],
            },
        ),
        migrations.CreateModel(
            name='JewelrySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the jewelry sub-category.', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Optional description of the jewelry sub-category.', max_length=250, null=True, verbose_name='Description')),
                ('category', models.ForeignKey(help_text='Jewelry category associated with this sub-category.', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='master.jewelrycategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Jewelry Sub Category',
                'verbose_name_plural': 'Jewelry Sub Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_jewe_active_f43d4f_idx'), models.Index(fields=['category'], name='master_jewe_categor_770326_idx')],
            },
        ),
    ]
