# Generated by Django 5.2.15 on 2026-08-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_jewelrycategory_jewelrysubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the template.', max_length=150, verbose_name='Name')),
                ('subject', models.CharField(blank=True, help_text='Email subject line to use with this template.', max_length=255, null=True, verbose_name='Subject')),
                ('template', models.TextField(blank=True, help_text='Template content — inline HTML/code, or a path/reference to a report template.', null=True, verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='master_temp_active_474d3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='POMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('name', models.CharField(help_text='Name of the P.O. Mail configuration.', max_length=150, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this configuration.', verbose_name='Order')),
                ('format1', models.OneToOneField(blank=True, help_text='Template used for Vendor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format1', to='master.templates', verbose_name='Format 1')),
                ('format2', models.OneToOneField(blank=True, help_text='Template used for Diamond Office.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format2', to='master.templates', verbose_name='Format 2')),
                ('format3', models.OneToOneField(blank=True, help_text='Template used for Color Stone Office.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format3', to='master.templates', verbose_name='Format 3')),
                ('format4', models.OneToOneField(blank=True, help_text='Template used for New York Office.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format4', to='master.templates', verbose_name='Format 4')),
            ],
            options={
                'verbose_name': 'P.O. Mail',
                'verbose_name_plural': 'P.O. Mails',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['active'], name='master_poma_active_3e0d36_idx')],
            },
        ),
    ]
