# Generated by Django 5.2.15 on 2026-09-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_terms_all_vendors_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findingitem',
            name='type',
        ),
        migrations.AlterField(
            model_name='findingitem',
            name='metal',
            field=models.ForeignKey(blank=True, help_text='Metal purity of the finding.', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.metalpurity', verbose_name='Finding Metal'),
        ),
        migrations.AddIndex(
            model_name='findingitem',
            index=models.Index(fields=['metal'], name='master_find_metal_i_a863fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='findingitem',
            constraint=models.UniqueConstraint(fields=('finding_type', 'name', 'metal'), name='unique_finding_item_metal'),
        ),
    ]
