# Generated by Django 5.2.15 on 2026-09-22 07:55

import django.core.validators
import django.db.models.deletion
import master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_remove_findingitem_type_alter_findingitem_metal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acexecutive',
            name='code',
            field=models.CharField(help_text='Optional code used to identify the accounts executive.', max_length=50, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='acexecutive',
            name='email',
            field=models.EmailField(help_text='Email address of the accounts executive.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='acexecutive',
            name='phone',
            field=models.CharField(help_text='Contact phone number of the accounts executive.', max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='courierservice',
            name='contact_person',
            field=models.CharField(help_text='Name of the primary contact person.', max_length=100, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='courierservice',
            name='email',
            field=models.EmailField(help_text='Email address for the courier service.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='courierservice',
            name='phone',
            field=models.CharField(help_text='Contact phone number for the courier service.', max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='courierservice',
            name='tracking_url',
            field=models.URLField(help_text='URL used to track shipments from this courier service.', max_length=500, null=True, verbose_name='Tracking URL'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='description',
            field=models.CharField(help_text='Optional description of the duty configuration.', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='findingitem',
            name='metal',
            field=models.ForeignKey(help_text='Metal purity of the finding.', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.metalpurity', verbose_name='Finding Metal'),
        ),
        migrations.AlterField(
            model_name='findingtype',
            name='description',
            field=models.CharField(help_text='Optional description of the finding type.', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='finishtype',
            name='description',
            field=models.CharField(help_text='Optional description of the finish type.', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jewelrycategory',
            name='description',
            field=models.CharField(help_text='Optional description of the jewelry category.', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jewelrysubcategory',
            name='description',
            field=models.CharField(help_text='Optional description of the jewelry sub-category.', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='laboursetting',
            name='setting',
            field=models.ForeignKey(help_text='Jewelry setting associated with this labour configuration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_settings', to='master.setting', verbose_name='Setting'),
        ),
        migrations.AlterField(
            model_name='metalpurity',
            name='karat',
            field=models.PositiveIntegerField(help_text='Karat value of the metal, e.g. 14, 18, 22, or 24.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kt'),
        ),
        migrations.AlterField(
            model_name='metaltype',
            name='description',
            field=models.CharField(help_text='Optional description of the metal type.', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.CharField(help_text='Optional description of the jewelry setting type.', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='description',
            field=models.CharField(help_text='Optional description of the stamp.', max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='image',
            field=models.ImageField(help_text='Optional image representing the hallmark or stamp.', null=True, upload_to=master.models.stamp_image, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='description',
            field=models.CharField(help_text='Optional description of the payment terms.', max_length=250, null=True, verbose_name='Description'),
        ),
    ]
