# Generated by Django 5.2.15 on 2026-09-23 07:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_order', '0003_rename_purchase_or_prepby_idx_purchase_or_prepby__464788_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('metal_sent_no', models.PositiveIntegerField(editable=False, help_text='Auto-generated sequential number for this metal sent record.', unique=True, verbose_name='Metal Sent No.')),
                ('invoice_no', models.CharField(help_text='Invoice number against which this metal was sent.', max_length=100, verbose_name='Invoice No.')),
                ('metal_sent_date', models.DateField(help_text='Date on which the metal was sent.', verbose_name='Metal Sent Date')),
                ('triounce', models.CharField(blank=True, help_text='Purity/fineness grade of the metal sent.', max_length=50, verbose_name='Triounce')),
                ('metal_gms', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Weight of metal sent, in grams.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metal Gms.')),
                ('metal_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Value of the metal sent.', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metal Amount')),
                ('prepby', models.ForeignKey(blank=True, help_text='User who created this metal sent record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_metal_sent_entries', to=settings.AUTH_USER_MODEL, verbose_name='Prepared By')),
                ('purchase_order', models.ForeignKey(help_text='Purchase order against which this metal was sent.', on_delete=django.db.models.deletion.PROTECT, related_name='metal_sent_entries', to='purchase_order.purchaseorder', verbose_name='P.O. No')),
            ],
            options={
                'verbose_name': 'Metal Sent',
                'verbose_name_plural': 'Metal Sent',
                'ordering': ['-metal_sent_date', '-metal_sent_no'],
                'indexes': [models.Index(fields=['invoice_no'], name='requisition_invoice_11323d_idx'), models.Index(fields=['metal_sent_date'], name='requisition_metal_s_264f81_idx'), models.Index(fields=['purchase_order'], name='requisition_purchas_23851b_idx'), models.Index(fields=['active'], name='requisition_active_77d650_idx')],
            },
        ),
    ]
