# Generated by Django 5.2.15 on 2026-09-23 08:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalsent',
            name='metal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Value of the metal sent. Can be negative for returns/adjustments.', max_digits=15, verbose_name='Metal Amount'),
        ),
        migrations.AlterField(
            model_name='metalsent',
            name='metal_gms',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Weight of metal sent, in grams. Can be negative for returns/adjustments.', max_digits=15, verbose_name='Metal Gms.'),
        ),
        migrations.AlterField(
            model_name='metalsent',
            name='triounce',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Purity/fineness grade of the metal sent.', max_digits=15, verbose_name='Triounce'),
        ),
    ]
