# Generated by Django 5.2.15 on 2026-09-29 07:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcard', '0009_alter_costcard_finding_item'),
        ('purchase_order', '0003_rename_purchase_or_prepby_idx_purchase_or_prepby__464788_idx'),
        ('requisition', '0002_alter_metalsent_metal_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FluteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('invoice_no', models.CharField(help_text='Invoice number for this flute entry.', max_length=100, verbose_name='Invoice No.')),
                ('flute_date', models.DateField(help_text='Date of the flute entry.', verbose_name='Flute Date')),
                ('prepby', models.ForeignKey(blank=True, help_text='User who created this flute entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_flute_entries', to=settings.AUTH_USER_MODEL, verbose_name='Prepared By')),
            ],
            options={
                'verbose_name': 'Flute Entry',
                'verbose_name_plural': 'Flute Entries',
                'ordering': ['-flute_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FluteEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('cts', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Stone weight in carats.', max_digits=15, verbose_name='Cts.')),
                ('stone_type', models.CharField(choices=[('diamond', 'Diamond'), ('color_stone', 'Color Stone')], default='diamond', help_text='Type of stone for this flute entry line.', max_length=50, verbose_name='Stone Type')),
                ('sets', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Number of sets.', max_digits=15, verbose_name='Sets')),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Rate applied for this flute entry line.', max_digits=15, verbose_name='Rate')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount for this flute entry line.', max_digits=15, verbose_name='Amount')),
                ('cost_card_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cost card rate for the selected style.', max_digits=15, verbose_name='Cost Card Rate')),
                ('cost_card', models.ForeignKey(help_text='Cost card/style selected for this flute entry line.', on_delete=django.db.models.deletion.PROTECT, related_name='flute_entry_lines', to='costcard.costcard', verbose_name='Our Style No.')),
                ('flute_entry', models.ForeignKey(help_text='Flute entry header for this line.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='requisition.fluteentry', verbose_name='Flute Entry')),
                ('purchase_order', models.ForeignKey(help_text='Purchase order selected for this flute entry line.', on_delete=django.db.models.deletion.PROTECT, related_name='flute_entry_lines', to='purchase_order.purchaseorder', verbose_name='P.O. No.')),
                ('stone_place', models.ForeignKey(blank=True, help_text='Stone placement on the jewelry piece.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flute_entry_lines', to='costcard.stoneplace', verbose_name='Stone Place')),
            ],
            options={
                'verbose_name': 'Flute Entry Line',
                'verbose_name_plural': 'Flute Entry Lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='fluteentry',
            index=models.Index(fields=['invoice_no'], name='requisition_invoice_a2b48b_idx'),
        ),
        migrations.AddIndex(
            model_name='fluteentry',
            index=models.Index(fields=['flute_date'], name='requisition_flute_d_914b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='fluteentry',
            index=models.Index(fields=['active'], name='requisition_active_e55e97_idx'),
        ),
        migrations.AddIndex(
            model_name='fluteentryline',
            index=models.Index(fields=['flute_entry'], name='requisition_flute_e_ff1a31_idx'),
        ),
        migrations.AddIndex(
            model_name='fluteentryline',
            index=models.Index(fields=['purchase_order'], name='requisition_purchas_1afe5c_idx'),
        ),
        migrations.AddIndex(
            model_name='fluteentryline',
            index=models.Index(fields=['cost_card'], name='requisition_cost_ca_e2c110_idx'),
        ),
        migrations.AddIndex(
            model_name='fluteentryline',
            index=models.Index(fields=['stone_type'], name='requisition_stone_t_9d3cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='fluteentryline',
            index=models.Index(fields=['active'], name='requisition_active_15deeb_idx'),
        ),
    ]
