# Generated by Django 5.2.15 on 2026-10-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDiaVendorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Balance Dia With Vendor Report',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CloseOrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Close Order Report',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostCardExportReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cost Card Export Report',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceValueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Invoice Value Report',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenOrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Open Order Report',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='POStatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'PO Status Report',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='POStoneStatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'PO Stone Status Report',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='POStoneValuationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'PO Stone Valuation Report',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
