# Generated by Django 5.2.15 on 2026-10-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsreport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicturePresentationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Picture Presentation Report',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
