# Generated by Django 5.2.15 on 2026-08-21 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costcard', '0001_initial'),
        ('company', '0081_company_city_company_code_company_country_and_more'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('potype', models.CharField(choices=[('REQUEST', 'Request'), ('ORDER', 'Order')], default='ORDER', help_text='Type of purchase order: REQUEST or ORDER.', max_length=20, verbose_name='PO Type')),
                ('pono', models.CharField(blank=True, editable=False, help_text='Auto-generated purchase order number.', max_length=100, verbose_name='PO Number')),
                ('npono', models.IntegerField(default=0, editable=False, help_text='Sequential number used in PO number generation.', verbose_name='Sequential PO No')),
                ('nyear', models.IntegerField(default=0, editable=False, help_text='Year component of the PO number.', verbose_name='PO Year')),
                ('podate', models.DateField(help_text='Date when the purchase order was created.', verbose_name='PO Date')),
                ('prepby', models.CharField(blank=True, help_text='Name of the person who prepared this PO.', max_length=100, verbose_name='Prepared By')),
                ('ddate', models.DateField(blank=True, help_text='Expected delivery date.', null=True, verbose_name='Delivery Date')),
                ('vcsdate', models.DateField(blank=True, help_text='Date confirmed by the vendor for shipping.', null=True, verbose_name='Vendor Confirmed Ship Date')),
                ('esdstone', models.DateField(blank=True, help_text='Expected stone delivery date.', null=True, verbose_name='ESD Stone')),
                ('customer_pono', models.CharField(blank=True, help_text='Customer reference PO number.', max_length=100, verbose_name='Customer PO No')),
                ('pocategory', models.CharField(blank=True, help_text='Category of the purchase order (e.g. Production, Sample).', max_length=100, verbose_name='PO Category')),
                ('rem', models.TextField(blank=True, help_text='Remarks for this purchase order.', verbose_name='Remarks')),
                ('note', models.TextField(blank=True, help_text='Internal notes for this purchase order.', verbose_name='Notes')),
                ('tqty', models.IntegerField(default=0, help_text='Total quantity across all line items.', verbose_name='Total Qty')),
                ('luser', models.CharField(blank=True, help_text='Username of the last person to modify this PO.', max_length=100, verbose_name='Last User')),
                ('canc_dt', models.DateField(blank=True, help_text='Date when this PO was cancelled.', null=True, verbose_name='Cancelled Date')),
                ('canc_rem', models.TextField(blank=True, help_text='Remarks entered when cancelling this PO.', verbose_name='Cancel Remarks')),
                ('canc_user', models.CharField(blank=True, help_text='Username of the person who cancelled this PO.', max_length=100, verbose_name='Cancelled By')),
                ('acexeid', models.ForeignKey(blank=True, help_text='Accounts executive responsible for this PO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='master.acexecutive', verbose_name='A/C Executive')),
                ('customerid', models.ForeignKey(blank=True, help_text='Customer this PO is placed against.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_pos', to='company.company', verbose_name='Customer')),
                ('linkid', models.ForeignKey(blank=True, help_text='Parent PO when this is an ORDER converted from a REQUEST.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_orders', to='purchase_order.purchaseorder', verbose_name='Linked PO')),
                ('stampid', models.ForeignKey(blank=True, help_text='Hallmark / stamp type for this PO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='master.stamp', verbose_name='Stamp')),
                ('termsid', models.ForeignKey(blank=True, help_text='Payment terms for this PO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='master.terms', verbose_name='Terms')),
                ('vendorid', models.ForeignKey(blank=True, help_text='Vendor this PO is placed with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_pos', to='company.company', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-podate', '-npono'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='Updated At')),
                ('active', models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Active')),
                ('styleno', models.CharField(blank=True, help_text='Internal style number for this line item.', max_length=100, verbose_name='Style No')),
                ('vstyleno', models.CharField(blank=True, help_text='Vendor style number for this line item.', max_length=100, verbose_name='Vendor Style No')),
                ('qty', models.IntegerField(default=0, help_text='Quantity ordered on this line.', verbose_name='Quantity')),
                ('size', models.CharField(blank=True, help_text='Comma-separated list of sizes (e.g. "7,8,9").', max_length=255, verbose_name='Size')),
                ('spcs', models.CharField(blank=True, help_text='Comma-separated list of pieces per size (e.g. "100,200,300").', max_length=255, verbose_name='Size Pieces')),
                ('stnoauto', models.IntegerField(default=0, help_text='Auto-generated stone sequence number.', verbose_name='Stone No Auto')),
                ('costcardid', models.ForeignKey(blank=True, help_text='Cost card associated with this line item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_lines', to='costcard.costcard', verbose_name='Cost Card')),
                ('poid', models.ForeignKey(help_text='Purchase order this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase_order.purchaseorder', verbose_name='Purchase Order')),
                ('vendorid', models.ForeignKey(blank=True, help_text='Vendor for this specific line item (overrides PO-level vendor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_line_vendors', to='company.company', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Purchase Order Line',
                'verbose_name_plural': 'Purchase Order Lines',
                'ordering': ['poid', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['active'], name='purchase_or_active_f83827_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['pono'], name='purchase_or_pono_e212c8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['potype'], name='purchase_or_potype_73d9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['pocategory'], name='purchase_or_pocateg_b713db_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['podate'], name='purchase_or_podate_c47dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['customerid'], name='purchase_or_custome_7283d5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendorid'], name='purchase_or_vendori_65509b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['active'], name='purchase_or_active_a791f3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['poid'], name='purchase_or_poid_id_2f5735_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['costcardid'], name='purchase_or_costcar_95b605_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['vendorid'], name='purchase_or_vendori_19bd5a_idx'),
        ),
    ]
