# Generated by Django 5.2.15 on 2026-08-26 09:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_costcard_parent"),
        ("company", "0081_company_city_company_code_company_country_and_more"),
        ("master", "0001_initial"),
        ("purchase_order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="POCostCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is currently active.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "costcardno",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the original cost card number.",
                        max_length=50,
                        verbose_name="Cost Card No",
                    ),
                ),
                (
                    "our_style_no",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the internal style number.",
                        max_length=100,
                        verbose_name="Our Style No",
                    ),
                ),
                (
                    "vendor_style_no",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the vendor style number.",
                        max_length=100,
                        null=True,
                        verbose_name="Vendor Style No",
                    ),
                ),
                (
                    "karat",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot karat value, e.g. 14KT, 18KT.",
                        max_length=20,
                        verbose_name="Kt",
                    ),
                ),
                (
                    "metal_grams",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="Snapshot weight of metal used, in grams.",
                        max_digits=10,
                        verbose_name="Metal Grams",
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Snapshot net weight of the piece.",
                        max_digits=10,
                        null=True,
                        verbose_name="Net Weight",
                    ),
                ),
                (
                    "gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Snapshot gross weight of the piece.",
                        max_digits=10,
                        null=True,
                        verbose_name="Gross Weight",
                    ),
                ),
                (
                    "troy_ounce_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Snapshot metal price per troy ounce.",
                        max_digits=15,
                        null=True,
                        verbose_name="Troy Ounce Price",
                    ),
                ),
                (
                    "finding_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot finding price.",
                        max_digits=15,
                        verbose_name="Finding Price",
                    ),
                ),
                (
                    "metal_loss_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot metal loss percentage.",
                        max_digits=6,
                        verbose_name="Metal Loss %",
                    ),
                ),
                (
                    "metal_loss_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot metal loss amount.",
                        max_digits=15,
                        verbose_name="Metal Loss Amount",
                    ),
                ),
                (
                    "metal_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot metal amount.",
                        max_digits=15,
                        verbose_name="Metal Amount",
                    ),
                ),
                (
                    "dia_pcs",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Snapshot total diamond piece count.",
                        verbose_name="Dia. Pcs",
                    ),
                ),
                (
                    "dia_cts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Snapshot total diamond carat weight.",
                        max_digits=10,
                        verbose_name="Dia. Cts",
                    ),
                ),
                (
                    "dia_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot total diamond cost.",
                        max_digits=15,
                        verbose_name="Dia. Amount",
                    ),
                ),
                (
                    "col_pcs",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Snapshot total color stone piece count.",
                        verbose_name="Col. Pcs",
                    ),
                ),
                (
                    "col_cts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Snapshot total color stone carat weight.",
                        max_digits=10,
                        verbose_name="Col. Cts",
                    ),
                ),
                (
                    "col_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot total color stone cost.",
                        max_digits=15,
                        verbose_name="Col. Amount",
                    ),
                ),
                (
                    "stone_pcs",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Snapshot combined stone piece count.",
                        verbose_name="Tot. Stone Pcs",
                    ),
                ),
                (
                    "stone_cts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Snapshot combined stone carat weight.",
                        max_digits=10,
                        verbose_name="Tot. Stone Cts",
                    ),
                ),
                (
                    "stone_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot combined stone cost.",
                        max_digits=15,
                        verbose_name="Tot. Stone Amount",
                    ),
                ),
                (
                    "labour_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot total labour cost.",
                        max_digits=15,
                        verbose_name="Labour Amount",
                    ),
                ),
                (
                    "dia_handling_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot diamond handling percentage.",
                        max_digits=6,
                        verbose_name="Dia. Handl. Charges %",
                    ),
                ),
                (
                    "dia_handling_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot diamond handling amount.",
                        max_digits=15,
                        verbose_name="Dia. Handl. Amount",
                    ),
                ),
                (
                    "col_handling_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot color stone handling percentage.",
                        max_digits=6,
                        verbose_name="Col. Handl. Charges %",
                    ),
                ),
                (
                    "col_handling_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot color stone handling amount.",
                        max_digits=15,
                        verbose_name="Col. Handl. Amount",
                    ),
                ),
                (
                    "vendor_markup_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot vendor markup percentage.",
                        max_digits=6,
                        verbose_name="Vendor Markup %",
                    ),
                ),
                (
                    "vendor_markup_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot vendor markup amount.",
                        max_digits=15,
                        verbose_name="Vendor Markup Amount",
                    ),
                ),
                (
                    "fob",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot free-on-board amount.",
                        max_digits=15,
                        verbose_name="F.O.B",
                    ),
                ),
                (
                    "duty_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot duty percentage.",
                        max_digits=6,
                        verbose_name="Duty %",
                    ),
                ),
                (
                    "duty_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot duty amount.",
                        max_digits=15,
                        verbose_name="Duty Amount",
                    ),
                ),
                (
                    "margin_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot profit margin percentage.",
                        max_digits=6,
                        verbose_name="Margin %",
                    ),
                ),
                (
                    "margin_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot profit margin amount.",
                        max_digits=15,
                        verbose_name="Margin Amount",
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Snapshot final computed cost.",
                        max_digits=15,
                        verbose_name="Final Amount",
                    ),
                ),
                (
                    "stnoauto",
                    models.IntegerField(
                        default=0,
                        help_text="Auto-generated stone sequence number copied from the PO line.",
                        verbose_name="Stone No Auto",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Snapshot jewelry category.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_costcards",
                        to="master.jewelrycategory",
                        verbose_name="Jewelry Category",
                    ),
                ),
                (
                    "costcard",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original CostCard reference (may be deleted later).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_snapshots",
                        to="cards.costcard",
                        verbose_name="Original Cost Card",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Snapshot customer for this piece.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_costcard_customers",
                        to="company.company",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "metal_purity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Snapshot metal purity grade.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_costcards",
                        to="master.metalpurity",
                        verbose_name="Metal Purity",
                    ),
                ),
                (
                    "poid",
                    models.ForeignKey(
                        help_text="Purchase order this snapshot belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="po_costcards",
                        to="purchase_order.purchaseorder",
                        verbose_name="Purchase Order",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Snapshot jewelry sub-category.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_costcards",
                        to="master.jewelrysubcategory",
                        verbose_name="Jewelry Sub Category",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Snapshot vendor for this piece.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_costcard_vendors",
                        to="company.company",
                        verbose_name="Vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "PO Cost Card",
                "verbose_name_plural": "PO Cost Cards",
                "ordering": ["poid", "id"],
            },
        ),
        migrations.CreateModel(
            name="POCostCardLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is currently active.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "etype",
                    models.CharField(
                        choices=[
                            ("DIAMOND", "Diamond"),
                            ("COLOURSTONE", "Colour Stone"),
                            ("FINISHTYPE", "Finish Type"),
                        ],
                        help_text="Which tab this frozen line came from: DIAMOND, COLOURSTONE or FINISHTYPE.",
                        max_length=20,
                        verbose_name="Line Type",
                    ),
                ),
                (
                    "stone",
                    models.CharField(
                        blank=True,
                        help_text="Frozen stone name (finish type name for FINISHTYPE lines).",
                        max_length=100,
                        null=True,
                        verbose_name="Stone",
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        blank=True,
                        help_text="Frozen shape name.",
                        max_length=100,
                        null=True,
                        verbose_name="Shape",
                    ),
                ),
                (
                    "cut",
                    models.CharField(
                        blank=True,
                        help_text="Frozen cut name.",
                        max_length=100,
                        null=True,
                        verbose_name="Cut",
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        blank=True,
                        help_text="Frozen colour name.",
                        max_length=100,
                        null=True,
                        verbose_name="Colour",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        blank=True,
                        help_text="Frozen quality name.",
                        max_length=100,
                        null=True,
                        verbose_name="Quality",
                    ),
                ),
                (
                    "mm_size",
                    models.CharField(
                        blank=True,
                        help_text="Frozen size name.",
                        max_length=100,
                        null=True,
                        verbose_name="MM Size",
                    ),
                ),
                (
                    "sieve_size",
                    models.CharField(
                        blank=True,
                        help_text="Frozen sieve size.",
                        max_length=50,
                        null=True,
                        verbose_name="Sieve Size",
                    ),
                ),
                (
                    "setting",
                    models.CharField(
                        blank=True,
                        help_text="Frozen setting name.",
                        max_length=100,
                        null=True,
                        verbose_name="Setting",
                    ),
                ),
                (
                    "stone_place",
                    models.CharField(
                        blank=True,
                        help_text="Frozen stone placement name.",
                        max_length=100,
                        null=True,
                        verbose_name="Stone Place",
                    ),
                ),
                (
                    "pointer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Frozen pointer value.",
                        max_digits=10,
                        null=True,
                        verbose_name="Pointer",
                    ),
                ),
                (
                    "pcs",
                    models.PositiveIntegerField(
                        default=0, help_text="Frozen piece count.", verbose_name="Pcs"
                    ),
                ),
                (
                    "cts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Frozen carat weight.",
                        max_digits=10,
                        verbose_name="Cts",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Frozen rate applied.",
                        max_digits=15,
                        verbose_name="Rate",
                    ),
                ),
                (
                    "pc",
                    models.CharField(
                        choices=[("P", "Per Piece"), ("C", "Per Carat")],
                        default="C",
                        help_text="Frozen rate unit: P = Per Piece, C = Per Carat.",
                        max_length=1,
                        verbose_name="P/C",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Frozen line amount.",
                        max_digits=15,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "labour_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Frozen labour rate.",
                        max_digits=15,
                        verbose_name="L.Rate",
                    ),
                ),
                (
                    "labour_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Frozen labour amount.",
                        max_digits=15,
                        verbose_name="L.Amount",
                    ),
                ),
                (
                    "default_rate",
                    models.BooleanField(
                        default=True,
                        help_text="Frozen D.R. flag (rate pulled from rate table).",
                        verbose_name="D.R.",
                    ),
                ),
                (
                    "po_costcard",
                    models.ForeignKey(
                        help_text="PO cost card snapshot this line belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchase_order.pocostcard",
                        verbose_name="PO Cost Card",
                    ),
                ),
            ],
            options={
                "verbose_name": "PO Cost Card Line",
                "verbose_name_plural": "PO Cost Card Lines",
                "ordering": ["po_costcard", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="pocostcard",
            index=models.Index(fields=["active"], name="purchase_or_active_9c0bb0_idx"),
        ),
        migrations.AddIndex(
            model_name="pocostcard",
            index=models.Index(fields=["poid"], name="purchase_or_poid_id_40544c_idx"),
        ),
        migrations.AddIndex(
            model_name="pocostcard",
            index=models.Index(
                fields=["costcard"], name="purchase_or_costcar_385f1f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pocostcard",
            unique_together={("poid", "costcard")},
        ),
        migrations.AddIndex(
            model_name="pocostcardline",
            index=models.Index(fields=["active"], name="purchase_or_active_6c9c55_idx"),
        ),
        migrations.AddIndex(
            model_name="pocostcardline",
            index=models.Index(
                fields=["po_costcard"], name="purchase_or_po_cost_a4bbc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pocostcardline",
            index=models.Index(fields=["etype"], name="purchase_or_etype_4a6a38_idx"),
        ),
    ]
