# Generated by Django 5.2.15 on 2026-09-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_purchaseorder_prepby_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_or_prepby__464788_idx',
            old_name='purchase_or_prepby_idx',
        ),
    ]
