# Generated by Django 5.2.15 on 2026-09-29 06:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0084_alter_contact_email"),
        ("master", "0009_alter_acexecutive_code_alter_acexecutive_email_and_more"),
        (
            "purchase_order",
            "0003_rename_purchase_or_prepby_idx_purchase_or_prepby__464788_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is currently active.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "vsno",
                    models.CharField(
                        blank=True,
                        help_text="Vendor invoice / shipment number.",
                        max_length=100,
                        verbose_name="Vendor Shipment No",
                    ),
                ),
                (
                    "vsdate",
                    models.DateField(
                        help_text="Date the vendor shipped the items.",
                        verbose_name="Shipment Date",
                    ),
                ),
                (
                    "trackref",
                    models.CharField(
                        blank=True,
                        help_text="Courier tracking reference for this shipment.",
                        max_length=255,
                        verbose_name="Tracking Reference",
                    ),
                ),
                (
                    "luser",
                    models.CharField(
                        blank=True,
                        help_text="Username of the last person to modify this shipment.",
                        max_length=100,
                        verbose_name="Last User",
                    ),
                ),
                (
                    "courierid",
                    models.ForeignKey(
                        blank=True,
                        help_text="Courier service used for this shipment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="master.courierservice",
                        verbose_name="Courier",
                    ),
                ),
                (
                    "vendorid",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vendor this shipment was received from.",
                        limit_choices_to={"is_supplier": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_shipments",
                        to="company.company",
                        verbose_name="Vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Shipment",
                "verbose_name_plural": "Vendor Shipments",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="VendorShipmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when this record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this record was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is currently active.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "pcs",
                    models.IntegerField(
                        default=0,
                        help_text="Number of pieces received.",
                        verbose_name="Pcs",
                    ),
                ),
                (
                    "metalwt",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="Metal weight received, in grams.",
                        max_digits=10,
                        verbose_name="Metal Wt.",
                    ),
                ),
                (
                    "diawt",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="Diamond weight received, in carats.",
                        max_digits=10,
                        verbose_name="Dia. Wt.",
                    ),
                ),
                (
                    "stplace",
                    models.CharField(
                        blank=True,
                        help_text="Stone placement for this line (Center/Side/Halo).",
                        max_length=100,
                        verbose_name="Stone Place",
                    ),
                ),
                (
                    "colwt",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="Color stone weight received, in carats.",
                        max_digits=10,
                        verbose_name="Col. Wt.",
                    ),
                ),
                (
                    "labour",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Labour cost of the received item.",
                        max_digits=15,
                        verbose_name="Labour",
                    ),
                ),
                (
                    "finding",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Finding cost of the received item.",
                        max_digits=15,
                        verbose_name="Finding",
                    ),
                ),
                (
                    "triounce",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Troy ounce rate applied to this received item.",
                        max_digits=10,
                        verbose_name="Troy Ounce",
                    ),
                ),
                (
                    "confrm",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="NULL = pending confirmation, True = confirmed.",
                        null=True,
                        verbose_name="Confirmed",
                    ),
                ),
                (
                    "costcardid",
                    models.ForeignKey(
                        blank=True,
                        help_text="PO cost card (style) this item was shipped against.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_lines",
                        to="purchase_order.pocostcard",
                        verbose_name="PO Cost Card",
                    ),
                ),
                (
                    "poid",
                    models.ForeignKey(
                        blank=True,
                        help_text="Purchase order this item was shipped against.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_lines",
                        to="purchase_order.purchaseorder",
                        verbose_name="Purchase Order",
                    ),
                ),
                (
                    "vendorshipid",
                    models.ForeignKey(
                        help_text="Shipment header this line belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vendor_shipment.vendorshipment",
                        verbose_name="Vendor Shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Shipment Line",
                "verbose_name_plural": "Vendor Shipment Lines",
                "ordering": ["vendorshipid", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="vendorshipment",
            index=models.Index(fields=["active"], name="vendor_ship_active_d62994_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorshipment",
            index=models.Index(fields=["vsno"], name="vendor_ship_vsno_675908_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorshipment",
            index=models.Index(fields=["vsdate"], name="vendor_ship_vsdate_e1dd35_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorshipment",
            index=models.Index(
                fields=["vendorid"], name="vendor_ship_vendori_7a3c91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorshipmentline",
            index=models.Index(fields=["active"], name="vendor_ship_active_5d205b_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorshipmentline",
            index=models.Index(
                fields=["vendorshipid"], name="vendor_ship_vendors_730226_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorshipmentline",
            index=models.Index(fields=["poid"], name="vendor_ship_poid_id_41e8e9_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorshipmentline",
            index=models.Index(
                fields=["costcardid"], name="vendor_ship_costcar_5a98d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorshipmentline",
            index=models.Index(fields=["confrm"], name="vendor_ship_confrm_786ba6_idx"),
        ),
    ]
