# Generated by Django 5.2.15 on 2026-10-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costcard", "0009_alter_costcard_finding_item"),
        ("vendor_shipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorshipmentline",
            name="costcardid",
            field=models.ForeignKey(
                blank=True,
                help_text="Cost card this item was shipped against.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipment_lines",
                to="costcard.costcard",
                verbose_name="Cost Card",
            ),
        ),
    ]
