# Generated by Django 5.2.15 on 2026-08-27 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Initial'), (10, 'Mapping Columns'), (20, 'Importing'), (30, 'Complete'), (40, 'Failed')], default=0)),
                ('data_file', models.FileField(blank=True, null=True, upload_to='data_import')),
                ('columns', models.JSONField(blank=True, null=True)),
                ('field_mapping', models.JSONField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('plugin', models.CharField(blank=True, max_length=100, null=True)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
