# Generated by Django 5.2.15 on 2026-08-20 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcard',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent cost card from which this card was copied.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_cards', to='cards.costcard', verbose_name='Parent Cost Card'),
        ),
    ]
