# Generated by Django 5.2.15 on 2026-09-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_remove_findingitem_type_alter_findingitem_metal_and_more'),
        ('users', '0015_alter_userprofile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='executive',
            field=models.ForeignKey(blank=True, help_text='Executive assigned to this ERP user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='master.acexecutive', verbose_name='Executive'),
        ),
    ]
